### PR TITLE
Add missing metadata for gitbook

### PR DESCRIPTION
**Pull request by cderv**
This PR adds some metadata used by Gitbook format and that are also used in bookdown.org

Specifically it adds your cover image link so that we can list the book in the main page of [bookdown.org](https://bookdown.org/) - related to https://github.com/rstudio/bookdown.org/pull/125

Currently, the book cover is not found (I believe because it is added using CSS and not directly in the index.Rmd body.

### CODE REVIEW

**Comment by juliasilge** [comment]
Thank you so much @cderv! 🙌  We are in the midst of some massive re-rendering right now for copyediting but we will get this merged in ASAP.

**Comment by cderv** [comment]
No hurry. I just think it would be nice to have this new book featured on bookdown.org and those metadata will be useful. 

It should also be useful if you want to share links on social media: https://bookdown.org/yihui/bookdown/features-for-html-publishing.html#metadata-for-sharing

**Comment by juliasilge** [comment]
Well @cderv if you took a look at this PR you may have seen some of the git gymnastics that have gone into getting our book "done". What a mess! In the commit that closed this PR ⬆️ I added those lines of metadata and we will get the book rendered again soon.

**Comment by cderv** [comment]
I see that 😅 Well done ! & Congratulations! 

I'll add the book to bookdown.org homepage once the metadata are there.

**Pull request closed without merging**
